version: '3.3'
services:
  database:
    platform: linux/x86_64
    image: mysql:5.7
    container_name: mysql
    restart: always
    environment:
      MYSQL_DATABASE: 'duonglien'
      MYSQL_ROOT_USER: 'root'
      MYSQL_USER: 'admin'
      MYSQL_PASSWORD: '123456'
      MYSQL_ROOT_PASSWORD: '123456'
    ports:
      - '3306:3306'
    expose:
      - '3306'